### ISSUE TITLE
Properly notifying ManageWP (and similar software) of Database updates.

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#2260]
## Issue Overview
Customer has 100+ sites running give, and uses a service like ManageWP to run plugin updates, core updates, etc. 

When a database update is needed, there's no way for the user to know without logging in to each individual site.

## Expected Behavior
A change that requires a DB update in order to continue receiving donations should throw some sort of alert that update is needed for services like ManageWP.

## Current Behavior
Donations just stop coming in, and by the time the agency is notified, multiple customers are upset. 

## Possible Solution
Investigate how/if those third party software services are alerted for updates to the database for WooCommerce, etc, and interface with them to come up with a solution.

## Steps to Reproduce (for bugs)
1. Install Give 1.7.2 on a fresh install in a live (non-local) environment.
2. Hook that install up to ManageWP or similar.
3. Run the update from 1.7.2 for the Give Core from within ManageWP or similar.
4. There will be need for a database update, but it doesn't show in ManageWP.

## Related Issues and/or PRs
#1538 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
I don't see any documentation or ways to implement db upgrades in ManageWP https://managewp.com/guide 

I found that ManageWP did a special integration with WooCommerce to notify of db upgrades: https://managewp.com/blog/woocommerce-database-updates-are-now-in-managewp

However that was done on their end. Since they're a SaaS I'm guessing it has to be done by them. 

I'm closing this issue since it's older and haven't heard much customer complaints since creation.
