### ISSUE TITLE
fix: use consistent key for currency decimals

### ISSUE THREAD

**Issue by raftaar1191** [impress-org/give#2655]
## Issue Overview
There is an inconsistency in localized variable key
Example: https://github.com/WordImpress/Give/blob/release/2.0/includes/scripts.php#L326 and https://github.com/WordImpress/Give/blob/release/2.0/includes/scripts.php#L48

Here you can see that both display give_get_price_decimals function value but the key is diff

## Expected Behavior
Must be same 

## Current Behavior
Not same

## Related Issues and/or PRs
https://github.com/WordImpress/Give/issues/339
https://github.com/WordImpress/Give-Fee-Recovery/issues/157

## Todos
- [x] Tests
- [x] Documentation

## WordPress Environment
<details>
```
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: 
TLS Connection: 
Server Info: nginx/1.10.1
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New Donor Registration✔Donor Register✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Admin Email Notifications: Disabled
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.3.7
Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.2.2

### Other Active Plugins ###


### Inactive Plugins ###

Braintree For WooCommerce Free: by Payment Plugins, support@paymentplugins.com – 2.6.20
Duplicate Post: by Enrico Battocchi – 3.2.1
Give - 2Checkout Gateway: by WordImpress – 1.0.2
Give - Authorize.net Gateway: by WordImpress – 1.3.2
Give - AWeber: by WordImpress – 1.0.2
Give - Braintree Gateway: by WordImpress – 1.1.1
Give - CCAvenue Gateway: by WordImpress – 1.0
Give - ConvertKit: by WordImpress – 1.0.1
Give - CSV Toolbox: by WordImpress – 1.0
Give - Display Donors: by WordImpress, LLC – 1.0
Give - Dwolla Gateway: by WordImpress – 1.1.2
Give - Email Reports: by WordImpress – 1.0.2
Give - Form Countdown: by WordImpress – 1.0
Give - Form Field Manager: by WordImpress – 1.2.4
Give - Gift Aid: by WordImpress – 1.0.0
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.1
Give - iATS Payment Solutions: by WordImpress – 1.0.1
Give - MailChimp: by WordImpress – 1.3.7
Give - Paymill Gateway: by WordImpress – 1.1
Give - PDF Receipts: by WordImpress – 2.2.2
Give - Recurring Donations: by WordImpress – 1.5.4
Give - Stripe Gateway: by WordImpress – 1.5.2
Give - Tributes: by WordImpress – 1.3.4
MailChimp for WordPress: by ibericode – 4.1.13
WooCommerce: by Automattic – 3.2.6
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.0
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.0.4

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

```
</details>

**Comment by kevinwhoffman** [comment]
@raftaar1191 please update this issue with more detail. The links in your original description are now broken since it appears that branch was deleted. Thanks.

**Comment by raftaar1191** [comment]
The localized of the variable key in inconsistent in Give Backend and Frontend.
Example for give_get_price_decimals() function in backend the key is [`currency_decimals `](https://github.com/WordImpress/Give/blob/release/2.0.7/includes/scripts.php#L324) and for frontend the key is [`number_decimals `](https://github.com/WordImpress/Give/blob/release/2.0.7/includes/scripts.php#L48). This key should be same for both frontend and backend variable that is being localized.


We should create a common function and pass this all value into it so that variable key will be consistent and also there will less repetition of code

**Comment by raftaar1191** [comment]
Related issues: https://github.com/WordImpress/Give/issues/2895

**Comment by kevinwhoffman** [comment]
@mehul0810 Please look into this briefly and let me know your thoughts on whether it is worth refactoring and whether doing so would affect any add-ons.

**Comment by mehul0810** [comment]
@kevinwhoffman I've investigated on this issue and noticed that there are 2 localized variables with the same value `number_decimals` and `currency_decimals`. Both the localized variables return the value from `give_get_price_decimals`. I've then checked the usage of the both the localized variables and found as below:

1. `number_decimals` - represents the same naming as per the setting field name. But, not used anywhere as introduced later on.
https://github.com/impress-org/give/blob/fe69c34756f54c9cc3eb88dbd3c00b1c6206a351/includes/class-give-scripts.php#L218

2. `currency_decimals` - doesn't represent the same naming as per the setting field name. But, used in Fee recovery add-on and `graph.php` file of core.
https://github.com/impress-org/give/blob/fe69c34756f54c9cc3eb88dbd3c00b1c6206a351/includes/class-give-scripts.php#L230

Now, When the currency switcher add-on is enabled, we use the data attributes from the `<form>` tag of donation form to fetch the dynamic value as per the screenshot below:
![image](https://user-images.githubusercontent.com/1852711/52250925-3ec06800-2920-11e9-8263-e0a7398fbbc2.png)

So, I would suggest using the data attributes from the `<form>` tag instead of localized variables for frontend where we can fetch the `<form>` tag of the donation form. But, in the case of admin, we need to use the localized variables so streamlining and rearranging the localized variable by keeping the related settings variables together will make more sense.
