### ISSUE TITLE
fix: remove Receipt ID from email template

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3032]
## User Story
As a site admin, I want to have the receipt id generate sequentially to provide better organization. 

## Current Behavior
I currently receive a long string as an id (ex. 5de4b465dd6329976f854023b4ad8ebf)

## Expected Behavior
I expect to have more organization when it comes to the receipt id

## Possible Solution
Generate a format Year-000000N, 2018-0000001 for the first donor, 2018-0000002 for the second donor,… and so on...

## Related
https://secure.helpscout.net/conversation/559709964/16842/
https://secure.helpscout.net/conversation/577579727/18162?folderId=1823994

**Comment by samsmith89** [comment]
You all have done a great job of implementing sequential ordering for donation id's in 2.1. Just wanted to look into the viability of doing this with receipt id's as well

**Comment by DevinWalker** [comment]
Thanks @samsmith89 - the function `give_pdf_get_payment_number()` uses the sequential ordering functionality. Therefore, this request should already be taken care of. The user would just have to update the prefix with the year `2018-` and then add number padding like they have. The only caveat is the admin would have to remember to update the prefix yearly since we don't have a auto-date based prefix generator like that yet.

**Comment by ravinderk** [comment]
@DevinWalker Your are right.

**Comment by kevinwhoffman** [comment]
I don't think we ended up including support for dynamic date tags in the sequential IDs. I'll discuss with Devin and report back to resolve this issue.

**Comment by kevinwhoffman** [comment]
Per discussion with @DevinWalker, we will remove `Receipt ID` from the email that is sent to the donor. It is not really visible anywhere else on the front end, and the hashed value doesn't mean anything to the donor. We will also deprecate the `{receipt_id}` tag since we don't want to encourage its use in emails.

**Comment by ravinderk** [comment]
@kevinwhoffman @DevinWalker  I found that another addon has there own `receipt_id` template tag:
- [ ] Give PDF Receipt ( In PDF receipt )
- [ ] Give Stripe ( In pre approval donor email )

Can we deprecate them also?

**Comment by kevinwhoffman** [comment]
Yes, we should remove `{receipt_id}` from from email templates across all add-ons.

@kakshak Can you submit PRs to remove the tag for the PDF Receipt and Stripe add-ons as well? Thank you.

**Comment by kevinwhoffman** [comment]
@kakshak To clarify from our team call, we want to remove the `{receipt_id}` from the email template and the list of tags below the editor, but we want to ensure that the tag continues to work in case existing users already have already included the tag in their email.

**Comment by kakshak** [comment]
@kevinwhoffman In `Give-PDF-Receipt` plugin, the `{transaction_key}` is used for `{receipt_id}`. So, should we need to remove that from email template tags? Because in that plugin `{receipt_id}` is also used and that is same as `{payment_id}`.

In Give Stripe plugin, I've removed it from pre-approval donor email. I've created branch `give/issue/3032` to reference this issue with Give plugin but I didn't create PR for that. Because this branch is from `release/2.1.2` which has a dependency on Give `v2.3.0` and this issue is related to Give `v2.3.1`. So, please let me know your thoughts about this.

**Comment by kevinwhoffman** [comment]
@kakshak I will review the Stripe emails more closely and clarify which tags should stay and which should be removed. I will also get back to you on which branch is appropriate to submit the PR for. Move on to other issues for now. Thanks.

**Comment by kevinwhoffman** [comment]
This is an old issue that has been blocked for some time. It is complicated by the fact that we use different language for Payment/Donation ID and Transacation ID as described in https://github.com/impress-org/give/issues/2306.

Closing as we have addressed the original point of confusion by removing the long hashed key from the email receipts. The Donation ID still remains in the browser receipt and email receipt.
