### ISSUE TITLE
refactor: remove duplicate `ajaxurl` from front-end

### ISSUE THREAD

**Issue by ravinderk** [impress-org/give#3471]
## User Story
We have multiple `ajaxurl` in frontend localize array, but we also have dedicated param for Ajax `ajax_vars ` in `ajaxurl` already defined.
https://github.com/impress-org/give/blob/master/includes/class-give-scripts.php#L443

Duplicated: https://github.com/impress-org/give/blob/master/includes/class-give-scripts.php#L406

**Comment by kakshak** [comment]
## Slack Call Summary

Participants: @kakshak, @ravinderk 
Topic: Need to discuss regarding duplicate `ajaxurl`
Result: I've confusion regarding to removing duplicate `ajaxurl` from all the add-ons or only from give and I confirmed that I need to remove from all the Give Add-on.

**Comment by mehul0810** [comment]
@DevinWalker @ravinderk 
PR of this issue is creating a sensitive bug on switching payment gateways as per the screenshot below.
![image](https://user-images.githubusercontent.com/1852711/46852823-dce06d80-ce19-11e8-9b12-66cdf1d14129.png)

Also, to point out, don't merge the PRs of new issues to release `2.3.0` if the issue is assigned to future releases as it will create a burden in testing issues as we won't be able to freeze the release `2.3.0`.

**Comment by kakshak** [comment]
## Slack Call Summary

Participants: @kakshak , @ravinderk 
Topic: Discussion on remove duplicate `ajaxurl` from front-end
Result: We will discuss this on further call. @ravinderk will look over it. Right now, we have confusion regarding remove duplicate `ajaxurl` from front-end. So, moving this issue to block.

**Comment by kevinwhoffman** [comment]
@ravinderk Please review this briefly and Icebox it if it's not a priority.

**Comment by ravinderk** [comment]
@kevinwhoffman It is not the priority, I will icebox it and assign to my self.
