### ISSUE TITLE
feat: disable Babel polyfill

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give#3658]
## User Story
As a user, I want to see an admin setting to disabled the babel polyfill js which is doing extra js call and I don't need IE 11 or lesser browser support so that it improves my site speed by reducing a js request.

Not all the users need support for IE11 and lesser browser versions as those are not the latest 2 versions. So, we should provide an option to disable babel polyfill js for those who don't need it. By default, we should have it enabled and a user can disable it based on the user preference.

## Acceptance Criteria
- [x] Add setting under the `Advanced` tab and add a detail description why you should disable it.

**Comment by kevinwhoffman** [comment]
Per discussion with @DevinWalker, we can point to this [existing snippet](https://github.com/impress-org/give-snippet-library/blob/10806fd0bf42b58acef3383c253afe6bab17955c/theme-compatibility/conditional-script-loading.php) if someone requests to remove the polyfill. In the meantime, we want most users to leave it enabled for donors who need the browser support.

**Comment by mathetos** [comment]
This isn't only our addons, but any other plugin or theme that might also use babel-polyfill. Is it possible to enqueue this in a `noConflict` sort of way, or prefixed to apply only to Give scripts?

If not, then a setting to empower users to fix these issues will help them NOT bail on using Give because it breaks their sites. 

Here's a current example:
https://wordpress.org/support/topic/breaking-sites-mobile-menu-on-install/

**Comment by kakshak** [comment]
@kevinwhoffman If we only need to prevent the conflicts with other themes and plugins that already enqueue `babel-polyfill.js` then I think we don't need to provide a separate option in `Advanced Setting` because right now, that condition is already handled in the plugin with below condition that if script has been not enqueued then only it will load in the plugin.

```
// Call Babel Polyfill with common handle so that it is compatible with plugins and themes.
if ( ! wp_script_is( 'babel-polyfill', 'enqueued' ) ) {
	wp_enqueue_script(
		'babel-polyfill',
		GIVE_PLUGIN_URL . 'assets/dist/js/babel-polyfill.js',
		array( 'jquery' ),
		GIVE_VERSION,
		false
	);
}
```

So, I think it doesn't make sense to provide an seprate option in `Advanced Setting (Tab)`. Please let me know your thoughts on this.

**Comment by kevinwhoffman** [comment]
@kakshak We try to avoid conflicts with `babel-polyfill` but that only works if the other theme/plugin is using the same `babel-polyfill` handle when registering the script. This is not a WordPress core handle, so there is no way we can guarantee others will use the same handle. Having an advanced setting will help users troubleshoot themselves or at least make the support process easier to resolve. Let's move forward with the setting.

**Comment by kevinwhoffman** [comment]
@kakshak Here is the description:

> Decide whether to load the Babel polyfill, which provides backwards compatibility for older browsers such as IE 11. The polyfill may be disabled to avoid conflicts with other themes or plugins that load the same script.

Also remember to move this setting below `Script Loading Location` setting.
