### ISSUE TITLE
feat: include custom columns in donor export CSV

### ISSUE THREAD

**Issue by Benunc** [impress-org/give#3709]
## User Story

As a third party developer, I want to add custom meta to the donor, and then be able to include that custom column on the user interface at Donations > Tools > export so that the end user can conditionally select the columns added to the CSV.

This requires a new filter to add that column to the user interface.

## Visuals
![screen shot 2018-09-27 at 12 43 31 pm](https://user-images.githubusercontent.com/9629102/46161235-04004200-c253-11e8-842a-f080d2a51842.png)

## Possible Solution
Add a filter here: https://github.com/WordImpress/Give/blob/master/includes/admin/tools/export/class-batch-export-donors.php#L217

## Acceptance Criteria

- [x] Research on best possible implementation.
- [x] Implement a new function `get_default_columns` to handle default columns list for export.
- [x] Add a filter `give_export_donor_get_default_columns` to the fn `get_default_columns`
- [x] Make the fn `get_default_columns` accessible in the view file `html-admin-page-exports.php`.
- [x] Populate the checkbox using the fn `get_default_columns` so that the opt-in donor fields and fields added via filter are loaded dynamically
- [x] Ensure that if custom meta field is added and checked then the same details are reflected in CSV with its related data.
- [x] Create a snippet to ensure it works properly.
- [x] Testing the snippet with the export functionality

## Related
- https://secure.helpscout.net/conversation/672073025/26317/
- https://github.com/WordImpress/Give-Snippet-Library/blob/master/donor/add-donor-meta.php

**Comment by simeonrowsell** [comment]
This is a feature requested by myself so just giving it the thumbs up! My clients have various custom donor meta (phone number for example), and being able to add these into the CSV they export would be hugely beneficial. Thanks

**Comment by kevinwhoffman** [comment]
@simeonrowsell Thanks for checking in. We are going to add this to our current sprint and get that filter in place for you.

@mehul0810 Please make sure once you add the filter to Give core, you also update the snippet to show how to use the filter so that the custom donor fields appear in the export screen. This has been defined in acceptance criteria above.

**Comment by kevinwhoffman** [comment]
@mehul0810 Thanks for looking into it. I have moved it to Blocked and we will discuss on next team call how to proceed.

**Comment by mehul0810** [comment]
Adding the updated Acceptance Criteria based on further investigation.

## Updated Acceptance Criteria
- [x] Research on best possible implementation.
- [ ] Implement a new function `get_default_columns` to handle default columns list for export.
- [ ] Add a filter `give_export_donor_get_default_columns` to the fn `get_default_columns`
- [ ] Make the fn `get_default_columns` accessible in the view file `html-admin-page-exports.php`.
- [ ] Populate the checkbox using the fn `get_default_columns` so that the opt-in donor fields and fields added via filter are loaded dynamically
- [ ] Ensure that if custom meta field is added and checked then the same details are reflected in CSV with its related data.
- [ ] Create a snippet to ensure it works properly.
- [ ] Testing the snippet with the export functionality

**Comment by mehul0810** [comment]
@kevinwhoffman I've created a PR for `release/2.2.6` as this issue is fixed now and we can release it in `2.2.6`. Let me know your thoughts.

**Comment by ravinderk** [comment]
@mehul0810 I think this issue resolved, so closing this.
