### ISSUE TITLE
fix: ensure the Invisible Recaptcha plugin doesn't prevent the donation confirmation page from loading

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3764]
# Bug Report

## User Story

As a site admin, I have issues with SPAM in my contact forms and have implemented the Invisible Recaptcha plugin. I have contact forms loaded into the footer widget areas so they are displayed on every page. I want my donors to not be taken to a 404 page on donation submissions so that they are not confused when they donate and they are presented with a donation confirmation page.

## Current Behavior

Whenever a donation is submitted the donor is taken to a 404 page.

## Expected Behavior

The donor to be redirected to the donation confirmation page.

## Bug Type
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install the Invisible Captcha plugin linked in this issue
2. Configure the plugin as I have in the screencast
3. Create a form using Contact Form 7
4. Put that form into a widget area that will display on every page
5. Submit a donation and see that you are taken to a 404 page.

## Visuals
Screencast of the issue:
https://screencast-o-matic.com/watch/cF6lo2YZOx

## Related
https://secure.helpscout.net/conversation/680748639/26930
https://secure.helpscout.net/conversation/682700260/27074
https://secure.helpscout.net/conversation/688503059/27531?folderId=848135

Link to plugin:
https://wordpress.org/plugins/invisible-recaptcha/

## Acceptance Criteria

- [ ] A donation is submitted with the Invisible Recaptcha enable in a separate form on the page

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.5
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report✔Renewal Receipt Email✔Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.2.3
Test Mode: Enabled
Currency Code: GBP
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card
Default Payment Gateway: Test Donation
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ✔ Licensed – by WordImpress – 1.4.3
Give - Braintree Gateway: ✔ Licensed – by WordImpress – 1.2.2
Give - CCAvenue Gateway: ✔ Licensed – by WordImpress – 1.0.2
Give - Email Reports: ✔ Licensed – by WordImpress – 1.1.2
Give - Gift Aid: ❌ Unlicensed – by WordImpress – 1.1.6
Give - MailChimp: ✔ Licensed – by WordImpress – 1.4.1
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4.1
Give - Paytm Gateway: ✔ Licensed – by WordImpress – 1.0.1
Give - PDF Receipts: ✔ Licensed – by WordImpress – 2.3
Give - Razorpay: ❌ Unlicensed – by WordImpress – 1.2.0
Give - Recurring Donations: ✔ Licensed – by WordImpress – 1.8.0
Give - Tributes: ✔ Licensed – by WordImpress – 1.5.0

### Other Active Plugins ###

Contact Form 7: by Takayuki Miyoshi – 5.0.4
Give - Fee Recovery: by GiveWP – 1.7.2
Give - Form Field Manager: by GiveWP – 1.4.0
Give - Google Analytics Donation Tracking: by GiveWP – 1.2.1
Give - Hook Helper: by Ravinder Kumar – 1.0
Give - PayPal Pro Gateway: by GiveWP – 1.2.0
Give - Stripe Gateway: by GiveWP – 2.1.1
Invisible reCaptcha: by Mihai Chelaru – 1.2.1
Sam's Helper Function: by WordImpress – 1.0
WooCommerce: by Automattic – 3.4.5
WordPress Importer: by wordpressdotorg – 0.6.4

### Inactive Plugins ###

All-in-One WP Migration: by ServMask – 6.73
Give - Donation Upsells for WooCommerce: by WordImpress – 1.0.3
User Role Editor: by Vladimir Garagulya – 4.44
WP Business Reviews: by Impress.org – 1.0.0

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by kevinwhoffman** [comment]
@kakshak See if you can recreate based on Sam's screencast and take steps to debug.

**Comment by kakshak** [comment]
@kevinwhoffman @samsmith89 I've tested this with Invisible Recaptcha plugin and it is working fine as per the expectation. So, I am not able to reproduce the issue. Below I attached the testing video for that.

Please let me know if I miss something over here.

## Video
https://www.useloom.com/share/8503b797502e47139d1906aa2439c18d

**Comment by samsmith89** [comment]
Just watched the video. I will test some more and get back here.

**Comment by samsmith89** [comment]
I just replicated the issue again on my Live site. 

Here is the screencast of my testing:
https://screencast-o-matic.com/watch/cF6DqgYUFG

Let me know if access to my live test site would be helpful, and I can provide that through Slack.

**Comment by kevinwhoffman** [comment]
Based on two customer reports and @samsmith89's screencast, I'm confident this is a real issue we should be able to reproduce, so let's keep going.

@kakshak I noticed differences between your screencast and @samsmith89's:

1. You are using the test gateway while Sam is using a credit card donation. Please try again using a Stripe to replicate. If that doesn't work try Authorize.net.
2 The environment info Sam provided says Give core 2.2.5 but there is a chance you may be testing on Give core 2.3.0 since that is current release branch. Check that your Give versions are the same and see if switching versions affects the outcome.

**Comment by kakshak** [comment]
@samsmith89 @kevinwhoffman I am able to reproduce this issue and I debug that it is causing the issue from Invisible Recaptcha plugin code. But need to do more debugging over it that if there is any possiblity to modify their code into ours.

**Comment by kakshak** [comment]
## Slack Call Summary

Participants: @kakshak , @ravinderk 
Topic: Discussion of comments form settings that produce 404 page
Result: I've confirmed with @ravinderk that, we have used a custom table for comments apart from using WP default comments table. I can check that if this is not reproduced in Give 2.3.0 version then add comment for that.

**Comment by kakshak** [comment]
@kevinwhoffman I've checked this issue and below is my review findings:
- [x] If this option `Enable Comments Form Protection` from Settings > Invisible reCaptcha > WordPress (Tab) is checked then it cause the issue in Give `v2.2.5`
- [x] It cause the issue in Give `v2.2.5` because we have used WP custom tables for that.
- [x] In Give `v2.3.0` somehow that is already resolved because we have used custom comments table in it.

# Video

## Video for Give version 2.2.5
https://www.useloom.com/share/57d855b2053340a886b2da4650294d08

## Video for Give version 3.0.0
https://www.useloom.com/share/8503b797502e47139d1906aa2439c18d

@kevinwhoffman Please confirm that.

**Comment by kevinwhoffman** [comment]
@kakshak Nice work debugging and thanks for the videos.

@samsmith89 Please review the videos and respond to the customer with the following.

1. When Give 2.3.0 releases next week, the conflict will be resolved because we have moved Give comments to a custom table.
2. In the meantime with Give 2.2.5, there is an option `Enable Comments Form Protection` that can be disabled in the recaptcha plugin that will prevent the 404 page and allow the donation to redirect to confirmation page successfully. See screenshot below for this option's location.

![image](https://user-images.githubusercontent.com/1938671/47224593-e756b600-d389-11e8-9c0b-9cf842c6fe4a.png)

**Comment by samsmith89** [comment]
Perfect. Thanks for letting me know, and I will respond to the customer.
