### ISSUE TITLE
feat: sort form grid by goal progress

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3818]
# Feature Request

## User Story

As a site admin, I want to order my form grid by those that are expiring soonest and by forms that are closest to meeting their goal so that can create a sense of urgency on particular forms.

## Possible Solution

Providing this as an option in the Give shortcode builder.

## Related
https://secure.helpscout.net/conversation/693671917/27970/

## Acceptance Criteria

- [x] I can sort forms by those closest to their goals.

**Comment by kevinwhoffman** [comment]
We'll handle this request in #3816 where we are currently extending the ordering functionality.

**Comment by kevinwhoffman** [comment]
@kakshak please consult with @mehul0810 as to whether either one of these is possible:

- Ordering forms by `Expiration`
    - I don't believe we have functionality for any type of expiration date unless the user has the [Form Countdown plugin](https://wordpress.org/plugins/give-form-countdown/) installed. If that plugin is a requirement, we should not pursue this ordering feature because the plugin is not widely used.
- Ordering forms by `Closest to Goal`
    - This might be possible but would require a complex query because we do not store a normalized percentage of progress. We only store the goal and current amount given.

**Comment by kakshak** [comment]
## Slack Call Summary

Participants: @kakshak , @mehul0810  
Topic: Discussion about provide option to sort form grid by expiring soonest and closest to goal.  
Result: I have talked with Mehul regarding the `Acceptance Criteria` and Ordering forms by `Closest to Goal` scenarios. I'll check the flow of Ordering forms by `Expiration` by using the `Form Countdown plugin` installed. Mehul explained me to the flow for how we can achieve the flow for `Closest to Goal`.

**Comment by kevinwhoffman** [comment]
@kakshak Do not worry about ordering by `Expiration` since that only applies to the Form Countdown add-on. Instead focus on ordering by `Closest to Goal` since that is a feature that would benefit all Give core users.

**Comment by kevinwhoffman** [comment]
## Slack Call Summary

Participants: @kakshak @ravinderk @kevinwhoffman 
Topic: How to sort forms by goal progress
Result: We agree there needs to be a new meta key added to each format that stores the normalized goal progress so that forms can be sorted by a common key no matter which type of goal is selected.

For example:

- $20 out of $25 =  80% goal progress
- 9 out of 10 donors = 90% goal progress
- 99 out of 100 donations = 99% goal progress

This goal progress would be updated when the form is saved or when a donation occurs. One concern regarding backwards compatibility is that a DB update would be required in order to add this normalized goal progress as form meta for existing forms.

Since this is a more complex implementation than the other order methods, I will discuss with @DevinWalker to decide whether to pursue the feature.

**Comment by kevinwhoffman** [comment]
@kakshak Devin confirmed in Slack that we can move forward on this feature. As we discussed above, this functionality will require a new form meta key to be added for each form going forward in addition to a database upgrade routine so that existing forms get the same key.

Please try writing the acceptance criteria yourself for this one and we can review together. Make sure to account for the following:

- How does this functionality work with new forms?
- How does this functionality work with existing forms?
- How is form progress kept up to date after a new donation?
- What happens when an admin changes the goal type?
- How is this option selected in the user interface?

**Comment by kakshak** [comment]
@kevinwhoffman I've added the acceptance criteria for this flow. Please review it and let me know about it.

**Comment by ravinderk** [comment]
@kakshak Review this commit: https://github.com/impress-org/give/compare/d8a061cc36be...382e42f77bea

@kakshak when sort form grid on basis of goal then admin form listing and front form list is different, can you review that?

@kevinwhoffmanthere there can be forms in Form Grid which do not has a goal but still, we are storing goal progress in meta key for sorting purpose. How do you want to sort these `0` goal based form list  ( as in admin list  or any custom logic )?

**Comment by kevinwhoffman** [comment]
@ravinderk Ideally all of the forms without goals set at all appear at the end of the list, after forms that do have goals without progress. This may require sorting by a secondary meta key so that the forms are grouped together like so:

- 80%
- 60%
- 40%
- 0%
- 0%
- 0%
- no goal set
- no goal set

**Comment by kakshak** [comment]
## Slack Call Summary

Participants: @kakshak @ravinderk 
Topics: Discussion on `No Goal Set` meta value
Discussion: I need to update the logic like if a goal is `disabled` for any form then update meta_key value to `-1` or `0.01 (decimal)`. If a goal is `enabled` then only meta_key update to either `0` value or `percentage` value based on settings.

**Comment by kakshak** [comment]
@ravinderk I've checked the `meta_key` value by updating with `-1` and it's working fine with this. Now, the forms are grouped together perfectly.
