### ISSUE TITLE
fix: improve text for anonymous donation checkbox

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give#3911]
# Bug Report

## User Story

As a donor I don't want to be confused by the anonymous donation checkbox if comments are disabled.

**See comments are not enabled but the text mentions a "Comment":**

![2018-12-20_12-50-06](https://user-images.githubusercontent.com/1571635/50310286-6635a100-0456-11e9-883d-9e1dfe6182b8.png)

## Expected Behavior

- If comments are disabled then the text should not reference a comment field.
- The word "administrator" is confusing and misleading for donors. It's singular and many sites have more than one admin. As well, the name and comment likely will be shared with more than just the administrator.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version `2.3.0`.

## Possible Solution

- Update the text to be conditional based on whether comments are enabled or not or just make the text more general.

## Related

Related to https://github.com/impress-org/give/issues/3826

## Acceptance Criteria

- [x] @mathetos 	@DevinWalker 	and @kevinwhoffman 	have discussed and agreed on an approach for the checkbox text.
- [x] Research what other websites like GoFundMe have for this text.

**Comment by kevinwhoffman** [comment]
The current line: `Hide name and comment from everyone but the administrator.`
was based on GoFundMe: `Hide name and comment from everyone but the organizer.`
but it makes more sense for GoFundMe because there is always a comment box.

I think we need to provide two different messages depending on whether comments are enabled.

**Comment by mathetos** [comment]
From a privacy perspective, I think this can serve multiple purposes and not be only dependent on the comments box. Donations and donor information can be queried in many ways and it would be the path of least resistance to consider this simply as a "consent" checkbox rather than paired only with the Comment field.

**Comment by kevinwhoffman** [comment]
At one point the text was more generic as shown in https://github.com/impress-org/give/issues/3826#issuecomment-440560600.

But then the anonymous behavior was changed so that anonymous donations would be displayed publicly by default but without name or comment. At that point the text was changed to be more specific.

I'm pointing this out to show that we've already gone from generic to specific language once, and going back to more generic consent language would reintroduce the ambiguity regarding what the checkbox actually does from a donor's perspective.

I think this can be solved more simply by making sure we don't mention comments if there is no comment field.

**Comment by kevinwhoffman** [comment]
@DevinWalker and I discussed how to clarify this language. Keeping in mind that the anonymous decision is made per donation, we decided on the following language. The tooltip will be modified based on whether comments are enabled for that form.

## With comment disabled

- Label: ` Make this an anonymous donation.`
- Tooltip: `Would you like to prevent your name and image from being displayed publicly?`

![image](https://user-images.githubusercontent.com/1938671/50998451-68d76380-14f5-11e9-9369-c31529c90ba2.png)

## With comment enabled

- Label: ` Make this an anonymous donation.`
- Tooltip: `Would you like to prevent your name, image, and comment from being displayed publicly?`

![image](https://user-images.githubusercontent.com/1938671/50998333-0da57100-14f5-11e9-810d-80c749ce4b0e.png)
