### ISSUE TITLE
fix: ensure updated email address is recipient when "Resend Receipt" is selected

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give#3933]
# Bug Report

## User Story

As a site admin, I want to resend a receipt to a donor that I had to update the email address for so that they can receive the the receipt they requested.

When the donor initially submitted their donation they input their email address incorrectly. They let me know, and I updated it for them in the backend of Give. I made the new email address the Primary and deleted the old email address. 

## Current Behavior
When I go to Resend Receipt in on the donation details page. The old email address is where the receipt sends. Not the updated Primary email address.

## Expected Behavior
I expect to have the power to change the email address for a donor, and when the Resend Receipt button is selected send to the updated email address, not the old one.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Create a donation with an incorrect email address
2. In the newly created donor add an email address to the donor making it the Primary address
3. Delete the original incorrect email
4. Navigate to one of the donations and resend the receipt
5. See that the email is sent to the original email address and not the updated one

## Visuals

Screencast of the issue:
https://screencast-o-matic.com/watch/cqV62D3jiX

## Possible Solution

1. Associate the donations to the Primary email address
2. Make a selection of which email to send to when the button is selected (if multiple)
3. Have a way to control the "Primary" email address on a per donation basis

## Related

https://secure.helpscout.net/conversation/732083074/31135

## Acceptance Criteria

- [ ] Provide a way to control the recipient email address when resending a donation receipt

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, in-progress, failed, acf-disabled, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed, refunded, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.1
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access✔Renewal Receipt Email✔Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.3.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Authorize.net
Default Payment Gateway: Test Donation
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ❌ Unlicensed – by GiveWP – 1.4.4
Give - Braintree Gateway: ❌ Unlicensed – by GiveWP – 1.2.3
Give - CCAvenue Gateway: ❌ Unlicensed – by GiveWP – 1.0.4
Give - Donation Upsells for WooCommerce: ❌ Unlicensed – by GiveWP – 1.1.0
Give - Fee Recovery: ❌ Unlicensed – by GiveWP – 1.7.4
Give - Form Field Manager: ❌ Unlicensed – by GiveWP – 1.4.1
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by GiveWP – 1.2.1
Give - MailChimp: ❌ Unlicensed – by GiveWP – 1.4.3
Give - Manual Donations: ❌ Unlicensed – by GiveWP – 1.4.2
Give - Mollie Gateway: ❌ Unlicensed – by WordImpress – 1.1.2
Give - PayPal Pro Gateway: ❌ Unlicensed – by GiveWP – 1.2.1
Give - Paytm Gateway: ✔ Licensed – by WordImpress – 1.0.1
Give - PDF Receipts: ❌ Unlicensed – by GiveWP – 2.3.2
Give - Recurring Donations: ❌ Unlicensed – by GiveWP – 1.8.2
Give - Stripe Gateway: ❌ Unlicensed – by GiveWP – 2.1.2
Give - Tributes: ❌ Unlicensed – by GiveWP – 1.5.2
Sam's Helper Function: ❌ Unlicensed – by WordImpress – 1.0

### Other Active Plugins ###

Advanced Custom Fields: by Elliot Condon – 5.7.7
Give - Hook Helper: by Ravinder Kumar – 1.0
Transients Manager: by Pippin Williamson – 1.7.5
User Role Editor: by Vladimir Garagulya – 4.47
WooCommerce: by Automattic – 3.5.2

### Inactive Plugins ###

All-in-One WP Migration: by ServMask – 6.78
Contact Form 7: by Takayuki Miyoshi – 5.0.4
Elementor: by Elementor.com – 2.3.2
Give - Email Reports: by WordImpress – 1.1.2
Give - Gift Aid: by WordImpress – 1.1.6
Give - GoCardless Gateway: by WordImpress – 1.2.1
Give - Razorpay: by WordImpress – 1.2.0
Gutenberg: by Gutenberg Team – 4.1.1
Intelligence: by LevelTen – 1.3.1
Invisible reCaptcha: by Mihai Chelaru – 1.2.1
WordPress Importer: by wordpressdotorg – 0.6.4
WP Business Reviews: by Impress.org – 1.0.0

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by samsmith89** [comment]
@kevinwhoffman I'm happy to take a look at this myself and see if I provide a solution.

**Comment by kevinwhoffman** [comment]
@samsmith89 I understand the frustration expressed by the customer because there is no way to resend a receipt to an address other than that one entered during donation. However it could also be confusing to click `Resend Receipt` and have it sent to the primary address which is different from address you see on screen in the current donation. We need to think through this a little further to see if we can clarify which address is being emails when you resend a receipt.

**Comment by kevinwhoffman** [comment]
@samsmith89 Devin and I discussed and we feel that always resending a receipt to the primary email may not always be the expected behavior. While the customer's case involves an incorrect email being entered, there are valid cases in which an alternative email would be used for different donations (personal vs. work email).

The safest assumption is the current behavior which resends the receipt to the same email entered during donation. The language "resend receipt" implies that the same email will be used.

The only way to make really clarify the action would be to add a UI for the admin to pick which email to send the receipt to, and that introduces a level of complexity in the UI we don't want to pursue for a rare use case.

## Workaround

Since the customer has a Plus Bundle, we recommend installing PDF Receipts and downloading the receipt which can then be sent to the donor's email. This is a one-time fix since future donations will use the email address entered during those donations.

## Future Improvements

This type of issue is part of an ongoing discussion around what type of data belongs to the donation and which belongs to the donor. In the future, a front-end donor profile editor will allow the donor to more explicitly define their own information (such as preferred email address) so that we don't have to make assumptions based on data gathered from donations over time.

**Comment by samsmith89** [comment]
@kevinwhoffman Sounds good. I'll follow up with the customer. Thanks for providing context

**Comment by robrecord** [comment]
I'm currently experiencing this issue and I feel the behaviour should be to default to the (new) primary email if the previous email is no longer listed. This would be great as I expect to have many of such queries to resolve.
