### ISSUE TITLE
feat: add donation notes to fields to be exported in donation export tool

### ISSUE THREAD

**Issue by mathetos** [impress-org/give#3979]
# Feature Request

## User Story

As a Give user, I want to run exports that include Donor Notes

If I add donor notes, either private or to the donor, to my donations, I expect to be able to export that information in the Donation Export feature. But currently that is not available. 

## Visuals
Current Fields available for export:
![image](https://user-images.githubusercontent.com/930724/52152017-d3c61700-2629-11e9-8aea-2ef97d291fa9.png)

## Related
- [HelpScout Request](https://secure.helpscout.net/conversation/768789507/33685?folderId=672194)
- [Additional request](https://secure.helpscout.net/conversation/773464805/34031/)

## Acceptance Criteria

- [x] "Donation Notes (private)" is an option listed in the list of fields in the "Donation Payment Fields" option (unchecked by default)
- [x] "Donation Notes (to donor)" is an option listed in the list of fields in the "Donation Payment Fields" option (unchecked by default)
- [x] When either or both are checked, the export includes those notes as a column in the export and correctly reflects the data associated with the correct donation.
- [x] Multiple notes are concatenated together, separated by a single line break (no separators necessary)
- [x] Each new note starts with the date of the note: `YYYY-MM-DD - Donation note text goes here.`

**Comment by kevinwhoffman** [comment]
@mathetos clarified in Slack that this is not the first request and recommended we raise the priority. Bumping this to the top of Product Backlog for next sprint.

**Comment by kevinwhoffman** [comment]
@mehul0810 Assigning this to you but I think we need to think through the implementation a bit more.

@mathetos When exporting donations, each donation in the exported CSV will be a single row in the spreadsheet. However there could be multiple notes of each type as shown below. This means we'll have to get all notes for the donation, and then concatenate them with a line break in between so that multiple notes appear as a stacked list within a single cell of the spreadsheet like so:

![image](https://user-images.githubusercontent.com/1938671/52767255-ebbd7380-2ff7-11e9-82b5-334ea083c908.png)

This could become unwieldy with longer, multi-paragraph notes. What do you think?

**Comment by ravinderk** [comment]
@kevinwhoffman You raised a good point about column height.
Next line will not a good solution to separate two notes because we are using `textarea` for the custom note and they can consist of multiple paragraphs.

Maybe we need a line separator symbol like `........`  or other



![image](https://user-images.githubusercontent.com/1784821/52767907-e0973180-3051-11e9-8ed1-1961d326d055.png)

![image](https://user-images.githubusercontent.com/1784821/52767923-e725a900-3051-11e9-9492-c20069572f8d.png)

**Comment by kevinwhoffman** [comment]
@ravinderk I also considered the line separator approach, but that would add even more lines to the column. I am wondering if a dedicated notes export would make more sense where each note would be displayed in its own row rather than trying to concatenate everything together into a single cell.

**Comment by kevinwhoffman** [comment]
@ravinderk and I reviewed the related Help Scout tickets and one of them is referring to an FFM field they are calling "note" and not the actual donation note functionality in WP admin. FFM fields are already supported in the export screen.

@Benunc you may want to follow up with the customer and let them know how to export custom fields. https://secure.helpscout.net/conversation/773464805/34031/

**Comment by ravinderk** [comment]
@Benunc I created custom FFM fields and export them

![image](https://user-images.githubusercontent.com/1784821/52769430-4685b800-3056-11e9-943a-ddfe466e39e5.png)

**Comment by kevinwhoffman** [comment]
@ravinderk I'm reassigning this to you. After review with Devin and Matt, we are going to move forward with the implementation described in https://github.com/impress-org/give/issues/3979#issuecomment-463508610 where all notes of each type are concatenated together in the same cell with a single line break separating them.

See updated Acceptance Criteria for full details.

**Comment by DevinWalker** [comment]
Resolved in #4018
