### ISSUE TITLE
test: improve coverage of acceptance testing

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give#4043]
# Feature Request

## User Story

As a Give developer, I want more acceptance tests to cover the most common Give user flows so that we can ensure bug-free releases and minimize our dependence on manual testing.

## Possible Solution

Start by getting your local environment set up using [this readme](https://github.com/impress-org/give/tree/02eaebbf5bb3ee1c11002b5ad949011053b8da3b/tests/e2e). Then proceed to write tests defined in the acceptance criteria below.

## Related

#4039 

## Acceptance Criteria

- [ ] A test confirms whether a logged-in user can successfully make a donation. (There are existing tests or logged-out users, but we specifically want to ensure that a logged-in user can donate).

**Comment by JasonTheAdams** [comment]
@kevinwhoffman Getting myself going with the Jest tests. I have composer and everything going, but I can't seem to get the tests to run. The containers are running, but when I run `npm run test` nothing seems to happen in the container. I've tried running it headless and otherwise, no dice.

I may need a hand troubleshooting this when you have a few minutes to chat, unless someone else is familiar with the acceptance test workflow?

**Comment by JasonTheAdams** [comment]
Well, I got jest to do something by running `brew install watchman && brew upgrade watchman` as learned from this issue: https://github.com/facebook/jest/issues/3436

However, the tests just fail for me. I have docker running and everything, but all the tests timeout and fail. I'll post back if I have any further success.

**Comment by DevinWalker** [comment]
Closing this issue in favor of creating individual issues per necessary test.
