### ISSUE TITLE
fix: new 2.5.0 licensing issues activating licenses

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give#4122]
## Issue Overview

After testing the new licensing updates in 2.5.0 I have found several issues.

### Video Demonstration

Please watch the following video for issues I had when testing the licensing:

https://drive.google.com/a/impress.org/file/d/1X4gvDiQdS1nzRFFEGveZDO3BxtfxYdt7/view?usp=drivesdk

#### Issues Found

- [x] Upgrading licenses incorrectly removed a license key as seen in the video: **Not need to change notice because this issue occurred only because Stripe add-ons readme setting was not configured properly on the staging site.**

- [x] After updating to `2.5.0` the previously active licenses are displaying as "Expired" incorrectly with dates that are not aligned with the licensing on GiveWP EDD Licensing.

- [x] Attempting to activate a license that has "Already been activated on this site" should ensure that the license can be activated. Right now that message displays in a confusing way and the license is never activated. This is hardly an ideal user experience. (See video below in "Updating Add-ons" for replicated demo): **Not need to change notice because this issue occurred only because Stripe add-ons readme setting was not configured properly on the staging site.**

### Activating All Access Pass

https://drive.google.com/a/impress.org/file/d/1w9v_jNyxkRCRpWnl_UYNmgMrOPsapfuk/view?usp=drivesdk

- [x] If I attempt to activate an All Access Pass in an individual add-on's license key field it should work the same as if I'm activating it in the main license metabox.

- [x] Some add-ons appear blank in the bundle list incorrectly.

- [x] The Stripe add-on for some reason appeared below the bundle incorrectly. It is part of the bundle and should be reflected as such.

### Updating Add-ons

https://drive.google.com/a/impress.org/file/d/1H9bDDNQRN10deaFVqwlSsV7utp4ECtP6/view?usp=drivesdk

### Testing from a New Customers Perspective

https://drive.google.com/a/impress.org/file/d/1L4OGuGSZEMwdzwvQdkuc7VK1-KXZjaPA/view?usp=drivesdk

This testing went pretty well. Please watch.

**Comment by ravinderk** [comment]
@DevinWalker

**Updating the license and wrong expiration date issue**
I can see we are testing with add-ons whose license expiration date exceeds subscription expiration date which is not possible. While discussing with you, I found that license expiration date and subscription expiration date can differ in that case we have to give priority to subscription. I can see we are seeing license date instead of subscription date on old Give plugin but it happens because I updated logic in new license API and functionality.
Can you test with update subscription expiration date? and let me know if you still can reproduce this.

**Stripe add-ons issue**
I noticed in the video that something strange happening only with stripe which we did not face while testing. I will look into this and let you know.

**Allow activating bundle license from add-on license activation form**
Can you confirm that what we should do here, can we show a notice that uses another form or just activate it. In my opinion, we must activate that because it is a global key.

**Comment by DevinWalker** [comment]
> Allow activating bundle license from add-on license activation form
> Can you confirm that what we should do here, can we show a notice that uses another form or just activate it. In my opinion, we must activate that because it is a global key.

Just activate it as normal as the user would expect and refresh to display bundle license and add-ons.

**Comment by DevinWalker** [comment]
## Licensing Review Round 2

I am still finding the following issues:

### 2.4.7 and below backwards compatibility 

https://drive.google.com/a/impress.org/file/d/1dfafgVZaMc0UEaotJhCpZ8hZcIZpCug-/view?usp=drivesdk

- [ ] Activating licenses in `2.4.7` displays the proper notice when a customer inserts a key for another add-on 

Note: A proper notice did display when attempting to activate a key that has hit its activation limit: https://drive.google.com/a/impress.org/file/d/14bxwsbOHBK5tkp9BTop4PgV3zjwoB9x6/view?usp=drivesdk

### Deactivating a site for a license via "My Account > Licenses" 

https://drive.google.com/a/impress.org/file/d/1Ps_JjDSeVVekkFZ1OlyEEcSZcVYX-hvD/view?usp=drivesdk

- [ ] The new licensing properly displays activation status when a customer deactivates a site on givewp.com

**Comment by ravinderk** [comment]
@DevinWalker Please confirm that you are on the latest code and still able to reproduce "**License subscription notice**"

**Comment by DevinWalker** [comment]
After our dev call:

1. I was unable to reliably reproduce this as well
2. Fixed
3. Fixed
