### ISSUE TITLE
chore: Design settings level vertical tabs based on wireframes

### ISSUE THREAD

**Issue by mikejhale** [impress-org/give#4205]
Design third level vertical setings based on wireframes provided by @mehul0810 for #4204

**Comment by DevinWalker** [comment]
## Third-level Navigational Settings Tabs

@mehul0810 here's the concept I have for the third-level tabs:

![2019-08-08_01-34-49](https://user-images.githubusercontent.com/1571635/62688050-e0cb1680-b97c-11e9-8f77-6b5e4f656645.png)

### Functional Notes

1. The tabs change on click (no page reload required)
2. Because they change on the fly the top level menu only goes to the `Stripe` base root.
3. The first tab's title and the first setting should align horizontally 
4. I changed "Stripe Settings" to just "Stripe"1
5. The main tab is bold and the unselected tabs are semi-bold

If you have any questions, let me know. If you like them and can proceed, then please close the issue.

**Comment by mikejhale** [comment]
Closing as development work has begun on third level settings tabs.
